### PR TITLE
Test with newer Rails versions

### PR DESCRIPTION
**Pull request by erdostom**
Also add mongoid 9

### CODE REVIEW

**Comment by moritzhoeppner** [comment]
Hi @erdostom, just fyi: I think some of the tests are failing because older Rails versions are not compatible with sqlite3 version 2. I hat the same problem and that's why I restricted the sqlite3 versions in my PR: https://github.com/erdostom/devise-argon2/pull/20/commits/e01639b8a4235e02b0afee284c4549814dd03948

**Comment by erdostom** [comment]
> Hi @erdostom, just fyi: I think some of the tests are failing because older Rails versions are not compatible with sqlite3 version 2. I hat the same problem and that's why I restricted the sqlite3 versions in my PR: [e01639b](https://github.com/erdostom/devise-argon2/commit/e01639b8a4235e02b0afee284c4549814dd03948)

thank you that worked

**Comment by moritzhoeppner** [comment]
I think the change of `ARGON2_VERSION` in https://github.com/erdostom/devise-argon2/pull/19/commits/ec44fe0a75580376a9fac73c8bda0ff31ca80e67 is not quite right. This is the version of our gem, not the ruby-argon2 version. So once you are releasing a new version, it should probably be changed to '2.0.2'. Or am I getting something wrong?

**Comment by erdostom** [comment]
wow good catch, thank you

reverted

**Pull request merged**
